pkcs11-tool: support verifying HMAC signatures
Before verification would only look for CKO_PUBLIC_KEY or
CKO_PRIVATE_KEY objects, however, for HMAC to work through C_Verify it
needs to look for CKO_SECRET_KEY objects as well.

Before:
tpm2pkcs11-tool --token-label=label --login --pin=myuserpin --verify --id='393837363534333231' --input-file=data.msg --mechanism=SHA-1-HMAC --signature-file=data.sig
error: Public key nor certificate not found
Aborting.

After:
tpm2pkcs11-tool --token-label=label --login --pin=myuserpin --verify --id='393837363534333231' --input-file=data.msg --mechanism=SHA-1-HMAC --signature-file=data.sig
Using signature algorithm SHA-1-HMAC
Signature is valid

To help promote extensibility in the future, various bits of meta data
can be associated with a mechanism via the mf_info table. The new bits
of metadata are MF_FLAGS and contain information to quickly acertain
what type of CKA_CLASS or C_.* interfaces are supported by the
mechanism. This table can be slowly populated over time so support for
other mechanisms can be added and the old code paths can be removed.

Signed-off-by: William Roberts <william.c.roberts@intel.com>