Revert last change, breaks building opensc: ../../src/libopensc/.libs/libopensc.so: undefined reference to `lt_dlopen' ...
git-svn-id: https://www.opensc-project.org/svnp/opensc/trunk@3208 c6295689-39f2-0310-b995-f0e70906c6a9