Fix lookup_enum_spec() prototype
A change introduced in c0072d16ddc7b52d2b2c3c53991f569dcac45b3a made the
compilation fail:
pkcs11-display.c:738:1: error: conflicting types for 'lookup_enum_spec'
pkcs11-display.h:64:13: note: previous declaration of 'lookup_enum_spec' was here