fuzz_pkcs15init.c: Fix FTBFS on ppc64el with gcc and O3
libtool: link: gcc -g -O0 -Wall -Wextra -Wno-unused-parameter -Werror -Wstrict-aliasing=2 -g -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fno-stack-clash-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/opensc-0.25.1-2ubuntu1 -O2 -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z -Wl,relro -o .libs/fuzz_piv_tool fuzz_piv_tool.o fuzzer_reader.o fuzzer_tool.o fuzzer.o ../../tools/util.o  -lcrypto ../../../src/libopensc/.libs/libopensc.so ../../../src/common/.libs/libscdl.a -ldl ../../../src/pkcs15init/.libs/libpkcs15init.a ../../../src/common/.libs/libcompat.a -pthread
fuzz_pkcs15init.c: In function ‘do_init_app’:
fuzz_pkcs15init.c:130:70: error: ‘BIT_FIELD_REF <info.attrs.pin, 64, 0>’ may be used uninitialized [-Werror=maybe-uninitialized]
  130 |     if ((info.attrs.pin.flags & SC_PKCS15_PIN_FLAG_UNBLOCK_DISABLED) &&
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  131 |         (info.attrs.pin.flags & SC_PKCS15_PIN_FLAG_SO_PIN))
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fuzz_pkcs15init.c:125:35: note: ‘BIT_FIELD_REF <info.attrs.pin, 64, 0>’ was declared here
  125 |     sc_pkcs15_auth_info_t         info;
      |                                   ^~~~
cc1: all warnings being treated as errors